# Generated by Django 3.1.6 on 2021-03-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_audio', models.FileField(blank=True, help_text='Allowed type - .wav, .ogg, .mp3, .m4a, .flac', upload_to='media/')),
                ('cloned_audio', models.FileField(blank=True, help_text='Allowed type - .wav, .ogg, .mp3, .m4a, .flac', upload_to='media/')),
            ],
        ),
    ]
